# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_mkldnn')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_mkldnn')
    _mkldnn = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mkldnn', [dirname(__file__)])
        except ImportError:
            import _mkldnn
            return _mkldnn
        try:
            _mod = imp.load_module('_mkldnn', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _mkldnn = swig_import_helper()
    del swig_import_helper
else:
    import _mkldnn
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def global_init():
    return _mkldnn.global_init()
global_init = _mkldnn.global_init

def enabled():
    return _mkldnn.enabled()
enabled = _mkldnn.enabled
class StreamFactory(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamFactory, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StreamFactory, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    if _newclass:
        getInstance = staticmethod(_mkldnn.StreamFactory_getInstance)
    else:
        getInstance = _mkldnn.StreamFactory_getInstance

    def getRELUFwdStream(self, input, output):
        return _mkldnn.StreamFactory_getRELUFwdStream(self, input, output)

    def setRELUFwdStream(self, input, output, layer):
        return _mkldnn.StreamFactory_setRELUFwdStream(self, input, output, layer)

    def getRELUBwdStream(self, input, output_diff, input_diff):
        return _mkldnn.StreamFactory_getRELUBwdStream(self, input, output_diff, input_diff)

    def setRELUBwdStream(self, input, output_diff, input_diff, layer):
        return _mkldnn.StreamFactory_setRELUBwdStream(self, input, output_diff, input_diff, layer)

    def getMaxPoolFwdStream(self, x_d1, x_d2, x_d3, x_d4, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w):
        return _mkldnn.StreamFactory_getMaxPoolFwdStream(self, x_d1, x_d2, x_d3, x_d4, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w)

    def setMaxPoolFwdStream(self, x_d1, x_d2, x_d3, x_d4, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer):
        return _mkldnn.StreamFactory_setMaxPoolFwdStream(self, x_d1, x_d2, x_d3, x_d4, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer)

    def setMaxPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer):
        return _mkldnn.StreamFactory_setMaxPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer)

    def getMaxPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w):
        return _mkldnn.StreamFactory_getMaxPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w)

    def getAvgPoolFwdStream(self, input, output, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w):
        return _mkldnn.StreamFactory_getAvgPoolFwdStream(self, input, output, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w)

    def setAvgPoolFwdStream(self, input, output, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer):
        return _mkldnn.StreamFactory_setAvgPoolFwdStream(self, input, output, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer)

    def setAvgPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer):
        return _mkldnn.StreamFactory_setAvgPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w, layer)

    def getAvgPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w):
        return _mkldnn.StreamFactory_getAvgPoolBwdStream(self, input_diff, output_diff, workspace, stride_y, stride_x, ksize_h, ksize_w, pad_l_h, pad_l_w, pad_r_h, pad_r_w)

    def getLRNFwdStream(self, input, output, local_size, alpha, beta):
        return _mkldnn.StreamFactory_getLRNFwdStream(self, input, output, local_size, alpha, beta)

    def setLRNFwdStream(self, input, output, local_size, alpha, beta, layer):
        return _mkldnn.StreamFactory_setLRNFwdStream(self, input, output, local_size, alpha, beta, layer)

    def getLRNBwdStream(self, input_diff, output_diff, local_size, alpha, beta):
        return _mkldnn.StreamFactory_getLRNBwdStream(self, input_diff, output_diff, local_size, alpha, beta)

    def setLRNBwdStream(self, input_diff, output_diff, local_size, alpha, beta, layer):
        return _mkldnn.StreamFactory_setLRNBwdStream(self, input_diff, output_diff, local_size, alpha, beta, layer)

    def getSoftmaxFwdStream(self, input, output, axis):
        return _mkldnn.StreamFactory_getSoftmaxFwdStream(self, input, output, axis)

    def setSoftmaxFwdStream(self, input, output, axis, layer):
        return _mkldnn.StreamFactory_setSoftmaxFwdStream(self, input, output, axis, layer)
    __swig_destroy__ = _mkldnn.delete_StreamFactory
    __del__ = lambda self: None
StreamFactory_swigregister = _mkldnn.StreamFactory_swigregister
StreamFactory_swigregister(StreamFactory)

def StreamFactory_getInstance():
    return _mkldnn.StreamFactory_getInstance()
StreamFactory_getInstance = _mkldnn.StreamFactory_getInstance

class Convolution2D_F32(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Convolution2D_F32, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Convolution2D_F32, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mkldnn.new_Convolution2D_F32()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _mkldnn.delete_Convolution2D_F32
    __del__ = lambda self: None

    def forward_setup(self, x, W, b, y, s1, s2, p1, p2):
        return _mkldnn.Convolution2D_F32_forward_setup(self, x, W, b, y, s1, s2, p1, p2)

    def forward(self, *args):
        return _mkldnn.Convolution2D_F32_forward(self, *args)

    def backward_setup(self, x, W, b, gy, gW, gx, gb):
        return _mkldnn.Convolution2D_F32_backward_setup(self, x, W, b, gy, gW, gx, gb)

    def backward(self, *args):
        return _mkldnn.Convolution2D_F32_backward(self, *args)
Convolution2D_F32_swigregister = _mkldnn.Convolution2D_F32_swigregister
Convolution2D_F32_swigregister(Convolution2D_F32)

class Pooling_F32(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pooling_F32, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pooling_F32, name)
    __repr__ = _swig_repr

    def forward(self, x, y):
        return _mkldnn.Pooling_F32_forward(self, x, y)

    def forward_setup(self, x_d1, x_d2, x_d3, x_d4, s_y, s_x, p_h, p_w, ker_h, ker_w, alg_kind):
        return _mkldnn.Pooling_F32_forward_setup(self, x_d1, x_d2, x_d3, x_d4, s_y, s_x, p_h, p_w, ker_h, ker_w, alg_kind)
    if _newclass:
        get_forward_object = staticmethod(_mkldnn.Pooling_F32_get_forward_object)
    else:
        get_forward_object = _mkldnn.Pooling_F32_get_forward_object

    def __init__(self):
        this = _mkldnn.new_Pooling_F32()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _mkldnn.delete_Pooling_F32
    __del__ = lambda self: None
Pooling_F32_swigregister = _mkldnn.Pooling_F32_swigregister
Pooling_F32_swigregister(Pooling_F32)

def Pooling_F32_get_forward_object(x, s_y, s_x, p_h, p_w, ker_h, ker_w, alg_kind):
    return _mkldnn.Pooling_F32_get_forward_object(x, s_y, s_x, p_h, p_w, ker_h, ker_w, alg_kind)
Pooling_F32_get_forward_object = _mkldnn.Pooling_F32_get_forward_object

class MaxPooling_F32(Pooling_F32):
    __swig_setmethods__ = {}
    for _s in [Pooling_F32]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MaxPooling_F32, name, value)
    __swig_getmethods__ = {}
    for _s in [Pooling_F32]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MaxPooling_F32, name)
    __repr__ = _swig_repr
    if _newclass:
        get_forward_object = staticmethod(_mkldnn.MaxPooling_F32_get_forward_object)
    else:
        get_forward_object = _mkldnn.MaxPooling_F32_get_forward_object

    def __init__(self):
        this = _mkldnn.new_MaxPooling_F32()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _mkldnn.delete_MaxPooling_F32
    __del__ = lambda self: None
MaxPooling_F32_swigregister = _mkldnn.MaxPooling_F32_swigregister
MaxPooling_F32_swigregister(MaxPooling_F32)

def MaxPooling_F32_get_forward_object(x, s_y, s_x, p_h, p_w, ker_h, ker_w):
    return _mkldnn.MaxPooling_F32_get_forward_object(x, s_y, s_x, p_h, p_w, ker_h, ker_w)
MaxPooling_F32_get_forward_object = _mkldnn.MaxPooling_F32_get_forward_object

class Layer_F32(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Layer_F32, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Layer_F32, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _mkldnn.delete_Layer_F32
    __del__ = lambda self: None

    def forward(self):
        return _mkldnn.Layer_F32_forward(self)

    def backward(self):
        return _mkldnn.Layer_F32_backward(self)

    def setup_forward(self):
        return _mkldnn.Layer_F32_setup_forward(self)

    def setup_backward(self):
        return _mkldnn.Layer_F32_setup_backward(self)

    def __init__(self):
        this = _mkldnn.new_Layer_F32()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
Layer_F32_swigregister = _mkldnn.Layer_F32_swigregister
Layer_F32_swigregister(Layer_F32)

class Relu_F32(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Relu_F32, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Relu_F32, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mkldnn.new_Relu_F32()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def forward_setup(self, x, y):
        return _mkldnn.Relu_F32_forward_setup(self, x, y)

    def forward(self, x, y):
        return _mkldnn.Relu_F32_forward(self, x, y)

    def backward_setup(self, x, gy, gx):
        return _mkldnn.Relu_F32_backward_setup(self, x, gy, gx)

    def backward(self, x, gy, gx):
        return _mkldnn.Relu_F32_backward(self, x, gy, gx)
    __swig_destroy__ = _mkldnn.delete_Relu_F32
    __del__ = lambda self: None
Relu_F32_swigregister = _mkldnn.Relu_F32_swigregister
Relu_F32_swigregister(Relu_F32)

# This file is compatible with both classic and new-style classes.


